version: '2.1'
services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/db/data
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./db/data:/data/db
    ports:
      - 27017:27017
    command: mongod --bind_ip_all --smallfiles --logpath=/dev/null # --quiet
        
  web:
    build: .
    links:
      - mongodb
    container_name: hapi.js
    restart: always
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - GMAIL_ID=${GMAIL_ID}
      - GMAIL_PASSWORD=${GMAIL_PASSWORD}
      - GMAIL_SENDEREMAIL=${GMAIL_SENDEREMAIL}
      - GMAIL_SENDERNAME=${GMAIL_SENDERNAME}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - SWAGGER_HOST=${SWAGGER_HOST}
      - JWT_SECRET=${JWT_SECRET}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - YAR_COOKIE_SECRET=${YAR_COOKIE_SECRET}
    depends_on:
      - mongodb